#Using multi stage

#build
FROM node:24-alpine3.21 AS builder
WORKDIR /app
COPY package.json package.json
COPY package-lock.json package-lock.json
RUN npm install 

COPY . .
RUN npm run build

#run
FROM node:24-alpine3.21 AS runner
WORKDIR /app
RUN npm install -g serve
COPY --from=builder /app/dist ./dist
EXPOSE 3000
CMD ["serve", "-s", "dist", "-l", "3000"]